#!/bin/sh
set -e
set -x

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- s3cmd "$@"
fi

DIR=/docker-entrypoint.d
if [[ -d "$DIR" ]]; then
  /bin/run-parts "$DIR"
fi

exec "$@"
