name: Mariadb 10.6 focal (@on-push)

on:
  push:
    branches:
      - main
      - refactor_workflow
    paths:
      - 'mariadb/_common/**'
      - 'mariadb/10.6/*/focal/*'
      - '.github/workflows/build-workflow.yml'
      - '.github/workflows/build-push-mariadb-10.6-focal.yml'

jobs:
  examine_tags:
    runs-on: ubuntu-latest
    steps:
      - id: examined_tags
        run: |
          curl -s -o newest_tag.json --header 'Authorization: ${{ secrets.SEMVER_API_TOKEN }}' 'https://sandbox-space-semver-api.deno.dev/tag/library/mariadb/newest?filter=^10\.6\.(\d%2B)-focal$'
          NEWEST_TAG=$(cat newest_tag.json | jq -c '.tags[0]')
          echo "NEWEST_TAG: $NEWEST_TAG"
          echo "::set-output name=newest_tag::${NEWEST_TAG}"
          
          curl -s -o list_tags.json --header 'Authorization: ${{ secrets.SEMVER_API_TOKEN }}' 'https://sandbox-space-semver-api.deno.dev/tag/library/mariadb/list?filter=^10\.6\.(\d%2B)-focal$'
          LIST_TAGS=$(cat list_tags.json | jq -c '.tags')
          echo "LIST_TAGS: $LIST_TAGS"
          echo "::set-output name=list_tags::${LIST_TAGS}"

          COUNT_TAGS=$(cat list_tags.json | jq '.tags' | jq 'length')
          echo "COUNT_TAGS: $COUNT_TAGS"
          echo "::set-output name=count_tags::${COUNT_TAGS}"
    outputs:
      newest_tag: ${{ steps.examined_tags.outputs.newest_tag }}
      list_tags: ${{ steps.examined_tags.outputs.list_tags }}
      count_tags: ${{ steps.examined_tags.outputs.count_tags }}

  build_tag:
    needs: examine_tags
    if: ${{ needs.examine_tags.outputs.count_tags > 0 }}
    uses:  sandbox-space/containers/.github/workflows/build-workflow.yml@main
    with:
      what: "mariadb"
      version: "10.6"
      environments: "prod dev"
      platform: "focal"
      placeholder_tag_value: "10.6.0-focal"
      build_tags: ${{ needs.examine_tags.outputs.list_tags }}
      newest_tag: ${{ needs.examine_tags.outputs.newest_tag }}
      push_repository_prefix: "sandboxspace/mariadb"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}